// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LekcRg/GophKeeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDB
func (_mock *MockDB) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDB_Expecter) Close() *MockDB_Close_Call {
	return &MockDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDB_Close_Call) Run(run func()) *MockDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Close_Call) Return(err error) *MockDB_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_Close_Call) RunAndReturn(run func() error) *MockDB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUser(ctx context.Context, user models.UserReq) (int, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) (int, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) int); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserReq) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepo_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(ctx context.Context, user models.UserReq)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserReq))
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(n int, err error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user models.UserReq) (int, error)) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByID(ctx context.Context, id int) (models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepo_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserRepo_GetUserByID_Call {
	return &MockUserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepo_GetUserByID_Call) Run(run func(ctx context.Context, id int)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) Return(user models.User, err error) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int) (models.User, error)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserRepo_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx
//   - login
func (_e *MockUserRepo_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *MockUserRepo_GetUserByLogin_Call {
	return &MockUserRepo_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockUserRepo_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserRepo_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepo_GetUserByLogin_Call) Return(user models.User, err error) *MockUserRepo_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (models.User, error)) *MockUserRepo_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserKey provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserKey(ctx context.Context, user models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserKey'
type MockUserRepo_UpdateUserKey_Call struct {
	*mock.Call
}

// UpdateUserKey is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepo_Expecter) UpdateUserKey(ctx interface{}, user interface{}) *MockUserRepo_UpdateUserKey_Call {
	return &MockUserRepo_UpdateUserKey_Call{Call: _e.mock.On("UpdateUserKey", ctx, user)}
}

func (_c *MockUserRepo_UpdateUserKey_Call) Run(run func(ctx context.Context, user models.User)) *MockUserRepo_UpdateUserKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserKey_Call) Return(err error) *MockUserRepo_UpdateUserKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserKey_Call) RunAndReturn(run func(ctx context.Context, user models.User) error) *MockUserRepo_UpdateUserKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserPassword(ctx context.Context, user models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockUserRepo_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepo_Expecter) UpdateUserPassword(ctx interface{}, user interface{}) *MockUserRepo_UpdateUserPassword_Call {
	return &MockUserRepo_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, user)}
}

func (_c *MockUserRepo_UpdateUserPassword_Call) Run(run func(ctx context.Context, user models.User)) *MockUserRepo_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserPassword_Call) Return(err error) *MockUserRepo_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, user models.User) error) *MockUserRepo_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVaultRepo creates a new instance of MockVaultRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultRepo {
	mock := &MockVaultRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVaultRepo is an autogenerated mock type for the VaultRepo type
type MockVaultRepo struct {
	mock.Mock
}

type MockVaultRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultRepo) EXPECT() *MockVaultRepo_Expecter {
	return &MockVaultRepo_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function for the type MockVaultRepo
func (_mock *MockVaultRepo) CreateItem(ctx context.Context, item models.VaultItem) (models.VaultItem, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 models.VaultItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultItem) (models.VaultItem, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultItem) models.VaultItem); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(models.VaultItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.VaultItem) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepo_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockVaultRepo_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *MockVaultRepo_Expecter) CreateItem(ctx interface{}, item interface{}) *MockVaultRepo_CreateItem_Call {
	return &MockVaultRepo_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockVaultRepo_CreateItem_Call) Run(run func(ctx context.Context, item models.VaultItem)) *MockVaultRepo_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.VaultItem))
	})
	return _c
}

func (_c *MockVaultRepo_CreateItem_Call) Return(vaultItem models.VaultItem, err error) *MockVaultRepo_CreateItem_Call {
	_c.Call.Return(vaultItem, err)
	return _c
}

func (_c *MockVaultRepo_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item models.VaultItem) (models.VaultItem, error)) *MockVaultRepo_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function for the type MockVaultRepo
func (_mock *MockVaultRepo) GetAllItems(ctx context.Context, userID int) ([]models.VaultItem, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []models.VaultItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.VaultItem, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.VaultItem); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VaultItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepo_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockVaultRepo_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *MockVaultRepo_Expecter) GetAllItems(ctx interface{}, userID interface{}) *MockVaultRepo_GetAllItems_Call {
	return &MockVaultRepo_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx, userID)}
}

func (_c *MockVaultRepo_GetAllItems_Call) Run(run func(ctx context.Context, userID int)) *MockVaultRepo_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockVaultRepo_GetAllItems_Call) Return(vaultItems []models.VaultItem, err error) *MockVaultRepo_GetAllItems_Call {
	_c.Call.Return(vaultItems, err)
	return _c
}

func (_c *MockVaultRepo_GetAllItems_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]models.VaultItem, error)) *MockVaultRepo_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockVaultRepo
func (_mock *MockVaultRepo) GetItem(ctx context.Context, id int) (models.VaultItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 models.VaultItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.VaultItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.VaultItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.VaultItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultRepo_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockVaultRepo_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockVaultRepo_Expecter) GetItem(ctx interface{}, id interface{}) *MockVaultRepo_GetItem_Call {
	return &MockVaultRepo_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *MockVaultRepo_GetItem_Call) Run(run func(ctx context.Context, id int)) *MockVaultRepo_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockVaultRepo_GetItem_Call) Return(vaultItem models.VaultItem, err error) *MockVaultRepo_GetItem_Call {
	_c.Call.Return(vaultItem, err)
	return _c
}

func (_c *MockVaultRepo_GetItem_Call) RunAndReturn(run func(ctx context.Context, id int) (models.VaultItem, error)) *MockVaultRepo_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBinaryURL provides a mock function for the type MockVaultRepo
func (_mock *MockVaultRepo) UpdateBinaryURL(ctx context.Context, req models.VaultConfirmBinaryUploadReq) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBinaryURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultConfirmBinaryUploadReq) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultRepo_UpdateBinaryURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBinaryURL'
type MockVaultRepo_UpdateBinaryURL_Call struct {
	*mock.Call
}

// UpdateBinaryURL is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockVaultRepo_Expecter) UpdateBinaryURL(ctx interface{}, req interface{}) *MockVaultRepo_UpdateBinaryURL_Call {
	return &MockVaultRepo_UpdateBinaryURL_Call{Call: _e.mock.On("UpdateBinaryURL", ctx, req)}
}

func (_c *MockVaultRepo_UpdateBinaryURL_Call) Run(run func(ctx context.Context, req models.VaultConfirmBinaryUploadReq)) *MockVaultRepo_UpdateBinaryURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.VaultConfirmBinaryUploadReq))
	})
	return _c
}

func (_c *MockVaultRepo_UpdateBinaryURL_Call) Return(err error) *MockVaultRepo_UpdateBinaryURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultRepo_UpdateBinaryURL_Call) RunAndReturn(run func(ctx context.Context, req models.VaultConfirmBinaryUploadReq) error) *MockVaultRepo_UpdateBinaryURL_Call {
	_c.Call.Return(run)
	return _c
}
