// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LekcRg/GophKeeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDB
func (_mock *MockDB) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDB_Expecter) Close() *MockDB_Close_Call {
	return &MockDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDB_Close_Call) Run(run func()) *MockDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDB_Close_Call) Return(err error) *MockDB_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDB_Close_Call) RunAndReturn(run func() error) *MockDB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUser(ctx context.Context, user models.UserReq) (int, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) (int, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) int); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserReq) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepo_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(ctx context.Context, user models.UserReq)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserReq))
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(n int, err error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user models.UserReq) (int, error)) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByID(ctx context.Context, id int) (models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserRepo_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserRepo_GetUserByID_Call {
	return &MockUserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepo_GetUserByID_Call) Run(run func(ctx context.Context, id int)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) Return(user models.User, err error) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int) (models.User, error)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByLogin(ctx context.Context, login string) (models.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserRepo_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx
//   - login
func (_e *MockUserRepo_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *MockUserRepo_GetUserByLogin_Call {
	return &MockUserRepo_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockUserRepo_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserRepo_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepo_GetUserByLogin_Call) Return(user models.User, err error) *MockUserRepo_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (models.User, error)) *MockUserRepo_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserKey provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserKey(ctx context.Context, user models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserKey'
type MockUserRepo_UpdateUserKey_Call struct {
	*mock.Call
}

// UpdateUserKey is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepo_Expecter) UpdateUserKey(ctx interface{}, user interface{}) *MockUserRepo_UpdateUserKey_Call {
	return &MockUserRepo_UpdateUserKey_Call{Call: _e.mock.On("UpdateUserKey", ctx, user)}
}

func (_c *MockUserRepo_UpdateUserKey_Call) Run(run func(ctx context.Context, user models.User)) *MockUserRepo_UpdateUserKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserKey_Call) Return(err error) *MockUserRepo_UpdateUserKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserKey_Call) RunAndReturn(run func(ctx context.Context, user models.User) error) *MockUserRepo_UpdateUserKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserPassword(ctx context.Context, user models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockUserRepo_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockUserRepo_Expecter) UpdateUserPassword(ctx interface{}, user interface{}) *MockUserRepo_UpdateUserPassword_Call {
	return &MockUserRepo_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", ctx, user)}
}

func (_c *MockUserRepo_UpdateUserPassword_Call) Run(run func(ctx context.Context, user models.User)) *MockUserRepo_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserPassword_Call) Return(err error) *MockUserRepo_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserPassword_Call) RunAndReturn(run func(ctx context.Context, user models.User) error) *MockUserRepo_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}
