// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GenPresignedGetURL provides a mock function for the type MockStorage
func (_mock *MockStorage) GenPresignedGetURL(ctx context.Context, filePath string) (string, error) {
	ret := _mock.Called(ctx, filePath)

	if len(ret) == 0 {
		panic("no return value specified for GenPresignedGetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, filePath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GenPresignedGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenPresignedGetURL'
type MockStorage_GenPresignedGetURL_Call struct {
	*mock.Call
}

// GenPresignedGetURL is a helper method to define mock.On call
//   - ctx
//   - filePath
func (_e *MockStorage_Expecter) GenPresignedGetURL(ctx interface{}, filePath interface{}) *MockStorage_GenPresignedGetURL_Call {
	return &MockStorage_GenPresignedGetURL_Call{Call: _e.mock.On("GenPresignedGetURL", ctx, filePath)}
}

func (_c *MockStorage_GenPresignedGetURL_Call) Run(run func(ctx context.Context, filePath string)) *MockStorage_GenPresignedGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GenPresignedGetURL_Call) Return(s string, err error) *MockStorage_GenPresignedGetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_GenPresignedGetURL_Call) RunAndReturn(run func(ctx context.Context, filePath string) (string, error)) *MockStorage_GenPresignedGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GenUploadPresignedURL provides a mock function for the type MockStorage
func (_mock *MockStorage) GenUploadPresignedURL(ctx context.Context, userID int) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GenUploadPresignedURL")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_GenUploadPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenUploadPresignedURL'
type MockStorage_GenUploadPresignedURL_Call struct {
	*mock.Call
}

// GenUploadPresignedURL is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *MockStorage_Expecter) GenUploadPresignedURL(ctx interface{}, userID interface{}) *MockStorage_GenUploadPresignedURL_Call {
	return &MockStorage_GenUploadPresignedURL_Call{Call: _e.mock.On("GenUploadPresignedURL", ctx, userID)}
}

func (_c *MockStorage_GenUploadPresignedURL_Call) Run(run func(ctx context.Context, userID int)) *MockStorage_GenUploadPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockStorage_GenUploadPresignedURL_Call) Return(url string, path string, err error) *MockStorage_GenUploadPresignedURL_Call {
	_c.Call.Return(url, path, err)
	return _c
}

func (_c *MockStorage_GenUploadPresignedURL_Call) RunAndReturn(run func(ctx context.Context, userID int) (string, string, error)) *MockStorage_GenUploadPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// IsContainsFile provides a mock function for the type MockStorage
func (_mock *MockStorage) IsContainsFile(ctx context.Context, path string) bool {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for IsContainsFile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStorage_IsContainsFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsContainsFile'
type MockStorage_IsContainsFile_Call struct {
	*mock.Call
}

// IsContainsFile is a helper method to define mock.On call
//   - ctx
//   - path
func (_e *MockStorage_Expecter) IsContainsFile(ctx interface{}, path interface{}) *MockStorage_IsContainsFile_Call {
	return &MockStorage_IsContainsFile_Call{Call: _e.mock.On("IsContainsFile", ctx, path)}
}

func (_c *MockStorage_IsContainsFile_Call) Run(run func(ctx context.Context, path string)) *MockStorage_IsContainsFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_IsContainsFile_Call) Return(b bool) *MockStorage_IsContainsFile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStorage_IsContainsFile_Call) RunAndReturn(run func(ctx context.Context, path string) bool) *MockStorage_IsContainsFile_Call {
	_c.Call.Return(run)
	return _c
}
