// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	"github.com/LekcRg/GophKeeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockUserService
func (_mock *MockUserService) ChangePassword(ctx context.Context, req models.UserChangePasswordReq) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserChangePasswordReq) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockUserService_Expecter) ChangePassword(ctx interface{}, req interface{}) *MockUserService_ChangePassword_Call {
	return &MockUserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, req)}
}

func (_c *MockUserService_ChangePassword_Call) Run(run func(ctx context.Context, req models.UserChangePasswordReq)) *MockUserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserChangePasswordReq))
	})
	return _c
}

func (_c *MockUserService_ChangePassword_Call) Return(err error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, req models.UserChangePasswordReq) error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetCryptoParams provides a mock function for the type MockUserService
func (_mock *MockUserService) GetCryptoParams(ctx context.Context, id int) (models.CryptoParamsRes, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCryptoParams")
	}

	var r0 models.CryptoParamsRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (models.CryptoParamsRes, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) models.CryptoParamsRes); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.CryptoParamsRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetCryptoParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCryptoParams'
type MockUserService_GetCryptoParams_Call struct {
	*mock.Call
}

// GetCryptoParams is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockUserService_Expecter) GetCryptoParams(ctx interface{}, id interface{}) *MockUserService_GetCryptoParams_Call {
	return &MockUserService_GetCryptoParams_Call{Call: _e.mock.On("GetCryptoParams", ctx, id)}
}

func (_c *MockUserService_GetCryptoParams_Call) Run(run func(ctx context.Context, id int)) *MockUserService_GetCryptoParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUserService_GetCryptoParams_Call) Return(cryptoParamsRes models.CryptoParamsRes, err error) *MockUserService_GetCryptoParams_Call {
	_c.Call.Return(cryptoParamsRes, err)
	return _c
}

func (_c *MockUserService_GetCryptoParams_Call) RunAndReturn(run func(ctx context.Context, id int) (models.CryptoParamsRes, error)) *MockUserService_GetCryptoParams_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, req models.UserReq) (models.APIKeyRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.APIKeyRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) (models.APIKeyRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) models.APIKeyRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(models.APIKeyRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockUserService_Expecter) Register(ctx interface{}, req interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, req models.UserReq)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserReq))
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(aPIKeyRes models.APIKeyRes, err error) *MockUserService_Register_Call {
	_c.Call.Return(aPIKeyRes, err)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, req models.UserReq) (models.APIKeyRes, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAPIKey provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateAPIKey(ctx context.Context, req models.UserLogin) (models.APIKeyRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAPIKey")
	}

	var r0 models.APIKeyRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserLogin) (models.APIKeyRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserLogin) models.APIKeyRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(models.APIKeyRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserLogin) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAPIKey'
type MockUserService_UpdateAPIKey_Call struct {
	*mock.Call
}

// UpdateAPIKey is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockUserService_Expecter) UpdateAPIKey(ctx interface{}, req interface{}) *MockUserService_UpdateAPIKey_Call {
	return &MockUserService_UpdateAPIKey_Call{Call: _e.mock.On("UpdateAPIKey", ctx, req)}
}

func (_c *MockUserService_UpdateAPIKey_Call) Run(run func(ctx context.Context, req models.UserLogin)) *MockUserService_UpdateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserLogin))
	})
	return _c
}

func (_c *MockUserService_UpdateAPIKey_Call) Return(aPIKeyRes models.APIKeyRes, err error) *MockUserService_UpdateAPIKey_Call {
	_c.Call.Return(aPIKeyRes, err)
	return _c
}

func (_c *MockUserService_UpdateAPIKey_Call) RunAndReturn(run func(ctx context.Context, req models.UserLogin) (models.APIKeyRes, error)) *MockUserService_UpdateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVaultService creates a new instance of MockVaultService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultService {
	mock := &MockVaultService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVaultService is an autogenerated mock type for the VaultService type
type MockVaultService struct {
	mock.Mock
}

type MockVaultService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultService) EXPECT() *MockVaultService_Expecter {
	return &MockVaultService_Expecter{mock: &_m.Mock}
}

// ConfirmBinaryUpload provides a mock function for the type MockVaultService
func (_mock *MockVaultService) ConfirmBinaryUpload(ctx context.Context, req models.VaultConfirmBinaryUploadReq) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmBinaryUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultConfirmBinaryUploadReq) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVaultService_ConfirmBinaryUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmBinaryUpload'
type MockVaultService_ConfirmBinaryUpload_Call struct {
	*mock.Call
}

// ConfirmBinaryUpload is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockVaultService_Expecter) ConfirmBinaryUpload(ctx interface{}, req interface{}) *MockVaultService_ConfirmBinaryUpload_Call {
	return &MockVaultService_ConfirmBinaryUpload_Call{Call: _e.mock.On("ConfirmBinaryUpload", ctx, req)}
}

func (_c *MockVaultService_ConfirmBinaryUpload_Call) Run(run func(ctx context.Context, req models.VaultConfirmBinaryUploadReq)) *MockVaultService_ConfirmBinaryUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.VaultConfirmBinaryUploadReq))
	})
	return _c
}

func (_c *MockVaultService_ConfirmBinaryUpload_Call) Return(err error) *MockVaultService_ConfirmBinaryUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVaultService_ConfirmBinaryUpload_Call) RunAndReturn(run func(ctx context.Context, req models.VaultConfirmBinaryUploadReq) error) *MockVaultService_ConfirmBinaryUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBinary provides a mock function for the type MockVaultService
func (_mock *MockVaultService) CreateBinary(ctx context.Context, req models.VaultItem) (models.VaultBinaryItemUploadRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBinary")
	}

	var r0 models.VaultBinaryItemUploadRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultItem) (models.VaultBinaryItemUploadRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultItem) models.VaultBinaryItemUploadRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(models.VaultBinaryItemUploadRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.VaultItem) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_CreateBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBinary'
type MockVaultService_CreateBinary_Call struct {
	*mock.Call
}

// CreateBinary is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockVaultService_Expecter) CreateBinary(ctx interface{}, req interface{}) *MockVaultService_CreateBinary_Call {
	return &MockVaultService_CreateBinary_Call{Call: _e.mock.On("CreateBinary", ctx, req)}
}

func (_c *MockVaultService_CreateBinary_Call) Run(run func(ctx context.Context, req models.VaultItem)) *MockVaultService_CreateBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.VaultItem))
	})
	return _c
}

func (_c *MockVaultService_CreateBinary_Call) Return(vaultBinaryItemUploadRes models.VaultBinaryItemUploadRes, err error) *MockVaultService_CreateBinary_Call {
	_c.Call.Return(vaultBinaryItemUploadRes, err)
	return _c
}

func (_c *MockVaultService_CreateBinary_Call) RunAndReturn(run func(ctx context.Context, req models.VaultItem) (models.VaultBinaryItemUploadRes, error)) *MockVaultService_CreateBinary_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItem provides a mock function for the type MockVaultService
func (_mock *MockVaultService) CreateItem(ctx context.Context, item models.VaultItem) (models.VaultItem, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 models.VaultItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultItem) (models.VaultItem, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.VaultItem) models.VaultItem); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(models.VaultItem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.VaultItem) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockVaultService_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx
//   - item
func (_e *MockVaultService_Expecter) CreateItem(ctx interface{}, item interface{}) *MockVaultService_CreateItem_Call {
	return &MockVaultService_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, item)}
}

func (_c *MockVaultService_CreateItem_Call) Run(run func(ctx context.Context, item models.VaultItem)) *MockVaultService_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.VaultItem))
	})
	return _c
}

func (_c *MockVaultService_CreateItem_Call) Return(vaultItem models.VaultItem, err error) *MockVaultService_CreateItem_Call {
	_c.Call.Return(vaultItem, err)
	return _c
}

func (_c *MockVaultService_CreateItem_Call) RunAndReturn(run func(ctx context.Context, item models.VaultItem) (models.VaultItem, error)) *MockVaultService_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItems provides a mock function for the type MockVaultService
func (_mock *MockVaultService) GetAllItems(ctx context.Context, id int) ([]models.VaultItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItems")
	}

	var r0 []models.VaultItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]models.VaultItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []models.VaultItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VaultItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_GetAllItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItems'
type MockVaultService_GetAllItems_Call struct {
	*mock.Call
}

// GetAllItems is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockVaultService_Expecter) GetAllItems(ctx interface{}, id interface{}) *MockVaultService_GetAllItems_Call {
	return &MockVaultService_GetAllItems_Call{Call: _e.mock.On("GetAllItems", ctx, id)}
}

func (_c *MockVaultService_GetAllItems_Call) Run(run func(ctx context.Context, id int)) *MockVaultService_GetAllItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockVaultService_GetAllItems_Call) Return(vaultItems []models.VaultItem, err error) *MockVaultService_GetAllItems_Call {
	_c.Call.Return(vaultItems, err)
	return _c
}

func (_c *MockVaultService_GetAllItems_Call) RunAndReturn(run func(ctx context.Context, id int) ([]models.VaultItem, error)) *MockVaultService_GetAllItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinaryFileURL provides a mock function for the type MockVaultService
func (_mock *MockVaultService) GetBinaryFileURL(ctx context.Context, userID int, vaultID int) (string, error) {
	ret := _mock.Called(ctx, userID, vaultID)

	if len(ret) == 0 {
		panic("no return value specified for GetBinaryFileURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (string, error)); ok {
		return returnFunc(ctx, userID, vaultID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) string); ok {
		r0 = returnFunc(ctx, userID, vaultID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userID, vaultID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVaultService_GetBinaryFileURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinaryFileURL'
type MockVaultService_GetBinaryFileURL_Call struct {
	*mock.Call
}

// GetBinaryFileURL is a helper method to define mock.On call
//   - ctx
//   - userID
//   - vaultID
func (_e *MockVaultService_Expecter) GetBinaryFileURL(ctx interface{}, userID interface{}, vaultID interface{}) *MockVaultService_GetBinaryFileURL_Call {
	return &MockVaultService_GetBinaryFileURL_Call{Call: _e.mock.On("GetBinaryFileURL", ctx, userID, vaultID)}
}

func (_c *MockVaultService_GetBinaryFileURL_Call) Run(run func(ctx context.Context, userID int, vaultID int)) *MockVaultService_GetBinaryFileURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockVaultService_GetBinaryFileURL_Call) Return(s string, err error) *MockVaultService_GetBinaryFileURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVaultService_GetBinaryFileURL_Call) RunAndReturn(run func(ctx context.Context, userID int, vaultID int) (string, error)) *MockVaultService_GetBinaryFileURL_Call {
	_c.Call.Return(run)
	return _c
}
