// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	"github.com/LekcRg/GophKeeper/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockUserService
func (_mock *MockUserService) ChangePassword(ctx context.Context, req models.UserChangePasswordReq) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserChangePasswordReq) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockUserService_Expecter) ChangePassword(ctx interface{}, req interface{}) *MockUserService_ChangePassword_Call {
	return &MockUserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, req)}
}

func (_c *MockUserService_ChangePassword_Call) Run(run func(ctx context.Context, req models.UserChangePasswordReq)) *MockUserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserChangePasswordReq))
	})
	return _c
}

func (_c *MockUserService_ChangePassword_Call) Return(err error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, req models.UserChangePasswordReq) error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockUserService
func (_mock *MockUserService) Login(ctx context.Context, req models.UserReq) (models.TokenUserRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 models.TokenUserRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) (models.TokenUserRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) models.TokenUserRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(models.TokenUserRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockUserService_Expecter) Login(ctx interface{}, req interface{}) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, req models.UserReq)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserReq))
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(tokenUserRes models.TokenUserRes, err error) *MockUserService_Login_Call {
	_c.Call.Return(tokenUserRes, err)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(ctx context.Context, req models.UserReq) (models.TokenUserRes, error)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, req models.UserReq) (models.TokenUserRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.TokenUserRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) (models.TokenUserRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserReq) models.TokenUserRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(models.TokenUserRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockUserService_Expecter) Register(ctx interface{}, req interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, req models.UserReq)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserReq))
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(tokenUserRes models.TokenUserRes, err error) *MockUserService_Register_Call {
	_c.Call.Return(tokenUserRes, err)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, req models.UserReq) (models.TokenUserRes, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
