basePath: /
definitions:
  models.APIKeyRes:
    properties:
      key:
        type: string
    type: object
  models.CryptoParamsRes:
    properties:
      encrypted_tag:
        type: string
      salt:
        type: string
    type: object
  models.Response:
    properties:
      message:
        type: string
    type: object
  models.ResponseError:
    properties:
      error:
        type: string
    type: object
  models.UserChangePasswordReq:
    properties:
      current-password:
        type: string
      login:
        type: string
      new-password:
        type: string
    type: object
  models.UserLogin:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  models.UserReq:
    properties:
      encrypted_tag:
        type: string
      login:
        type: string
      password:
        type: string
      salt:
        type: string
    type: object
info:
  contact: {}
  description: Gophkeeper password manager HTTP API
  title: GophKeeper API
  version: "1.0"
paths:
  /user/api-key:
    post:
      consumes:
      - application/json
      description: Create or update user API Key
      parameters:
      - description: Login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIKeyRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserLogin'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: API Key generation
      tags:
      - Users
  /user/change-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Current password and new password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserChangePasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserChangePasswordReq'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - Users
  /user/create:
    post:
      consumes:
      - application/json
      description: Register user and return API Key
      parameters:
      - description: Login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIKeyRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserReq'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.UserReq'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      summary: Register user
      tags:
      - Users
  /user/crypto-params:
    get:
      consumes:
      - application/json
      description: Get crypto params
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CryptoParamsRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.UserLogin'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.UserLogin'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseError'
      security:
      - BearerAuth: []
      summary: Get crypto params
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
